#!/usr/bin/env bash
# script redirects permanently
sudo apt update -y
sudo apt install nginx -y
sudo ufw 'Nginx HTTP'
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/channel\/UC9YcTIQuhwgoOQqYMKYqW9A permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default
sudo service nginx restart
