#!/usr/bin/env bash
# script creates a custom 404 error page
sudo apt update -y
sudo apt install nginx -y
sudo ufw 'Nginx HTTP'
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/channel\/UC9YcTIQuhwgoOQqYMKYqW9A permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

var="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$var/" /etc/nginx/sites-enabled/default

sudo service nginx restart
