#!/usr/bin/env bash
# the command displays the invincible message
# sigterm is a means to convey the message
while true
do
echo 'To infinity and beyond'
sleep 2
trap "echo 'I am invincible!!!'" SIGTERM 
done
