#!/usr/bin/env bash
# these are contents of the `/etc/passwd` file.
echo "User info from /etc/passwd:"
while IFS=':' read -r username password userid groupid userdesc homedir shell; do
echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
echo "$userid  place is protected by the passcode $password, more info about the user here: $userdesc"
done < /etc/passwd
