#!/usr/bin/env bash
# the loop is from 1-10 & displays:
# {bad-luck} on the 4th iteration
# {good-luck} on the 8th iteration
# {best-school} in all the remainig iterations
myCounter=0
while [ $myCounter -lt 10 ]
do
if [ $myCounter -eq 3 ]
then
echo "bad luck"
elif [ $myCounter -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
(( myCounter++ ))
done
