#!/usr/bin/env bash
#using case statment
i=1
while [ $i -le 20 ]
do
echo "$i"
i=$((i+1))
case $i in
5)
echo "bad luck from China"
;;
10)
echo "bad luck from Japan"
;;
18)
echo "bad luck from Italy"
;;
esac
done
