#!/usr/bin/env bash
#Displays all active IPv4 IPs on the machine it’s executed on
# ifconfig | grep -E -o  '([0-9]{1,3}\.){3}[0-9]{1,3}'
# ifconfig | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | cut -d/ -f1
ip -4 addr show | awk '/inet / {print $2}' | cut -d/ -f1
